- hooks/checkout
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arromer/github-fetch-buildkite-plugin/3)
> Add workaround for GitHub git lfs api rate limit error.

- hooks/checkout
this will at least make sure we stay in the same branch even if the head moves during the build.
we still need to handle the case of commit id being `HEAD`, but this at least will improve things.
> make sure we checkout the correct branch if BUILDKITE_COMMIT is HEAD

- .gitignore
- README.md
- hooks/checkout
To add a configuration knob to allow users to define timeout for `Git` remote operations.
If GitHub is flaky, the git remote operations (fetch, pull, push) block for quite a long time and then either fail or cause the whole checkout step to time out.
To leverage the `coreutils`'s `timeout` command so that we can fail fast when GitHub is experiencing issues and return a particular exit code so that Buildkite can be configured to perform automatic retries.
- Added / updated documentation.
- Added basic `.gitignore`.
> Add timeout for git remote operations

- hooks/checkout
This allows for better caching when we have a lot of jobs fetching the same commit: instead of checking the ref upstream every time we can fetch the commit we care about, regardless of which commit the ref is pointing to.
> Fetch only the specific commit.

- hooks/checkout
Handles this kind of error:
```
error: Server does not allow request for unadvertised object abcde12345
```
> Make fetching specific commit safer.

- hooks/checkout
`exit_code` was being set only on command failure, which meant that if it wasn't reset to `0` explicitly previous failing exit codes could carry over successful commands. To fix this always set `exit_code` to the commands' exit code regardless of whether they fail or succeed.
> Always set exit_code.

- hooks/checkout
This can for example be set to `set -x` to enable tracing, or even `export GIT_TRACE=1; set -x` to enable both bash tracing and git tracing.
> Add BUILDKITE_PLUGIN_GITHUB_FETCH_BASH_PREFIX to help debugging.

- hooks/checkout
https://github.com/arromer/github-fetch-buildkite-plugin/pull/15 didn't handle this correctly as it would exit the script because of `set -e`. Instead reset it to 0 every time.
> Reset exit code.

- hooks/checkout
Exiting from the function prevents the caller from reading the exit code.
> Return the exit code instead of exiting.

- hooks/checkout
This uses `--notags` to reduce the amount of refs we query from the server.
Officially this prevents fetching tags of objects that are reachable: https://git-scm.com/docs/git-pull#Documentation/git-pull.txt---no-tags
Testing shows that without it when fetching a branch git will fetch all tags, but will then ignore the ones that aren't reachable (this is up to the server probably):
Without `--notags`
```
11:21:04.548790 git.c:439               trace: built-in: git fetch -v origin master
11:21:04.668223 run-command.c:663       trace: run_command: unset GIT_PREFIX; GIT_PROTOCOL=version=2 ssh -o SendEnv=GIT_PROTOCOL git@github.com 'git-upload-pack '\''Canva/canva.git'\'''
11:21:06.978276 pkt-line.c:80           packet:        fetch< version 2
11:21:06.978294 pkt-line.c:80           packet: …
```
> Use --notags to skip ref advertisement.

- hooks/checkout
Added in https://github.com/arromer/github-fetch-buildkite-plugin/pull/19 the flag is `--no-tags`, not `--notags`.
> Fix --no-tags.

- hooks/checkout
add a little more visibility to whether we are getting the checkout from S3 or clone, and also get an idea of how long each step takes.
> add some logging to checkout hook

- hooks/checkout
Reverts arromer/github-fetch-buildkite-plugin#22
reverting this so that if we update the plugin it doesn't carry the checkout logic change.
> Revert "add support to replace repo base url"

- hooks/checkout
Using the buildkite agent to set a piece of metadata which can be used by subsequent steps to check whether a checkout executed successfully.
> Checkout Metadata

- hooks/checkout
this sets the origin url to the one in `BUILDKITE_REPO`, in case the checkout in the agent has a different origin.
> set remote url before checkout

- hooks/checkout
- hooks/pre-checkout
- plugin.yml
Add a pre-checkout hook so that we can use a github app to do the checkout instead of using SSH keys from the agent.
tested here: https://buildkite.com/canva-org/canva-web-build/builds/329147
> enable checkout using a github app

- hooks/pre-checkout
this fixes an issue when invoking a lambda using the aws cli v2:
```
Invalid base64: "{
"AppID": "85068",
"SecretId": "/nix-ci/github/app_private_key"
}"
```
cli v2 requires passing the `--cli-binary-format raw-in-base64-out` parameter.
All agents are being migrated to use aws cli v2, so we need to update this to be able to checkout the repo using a github app.
> fix lambda invoke on aws cli v2

- hooks/checkout
retries are not working:
```
[2021-04-08 02:00:49] INFO: Fetch BUILDKITE_COMMIT=b5abee35f11f8b57b20c5ef54b6553283c0d1375
--
  | [2021-04-08 02:06:50] INFO: Commit SHA b5abee35f11f8b57b20c5ef54b6553283c0d1375 does not exists. The ref might have been force pushed.
  | [2021-04-08 02:06:50] INFO: main:Checkout failed with error code=116. retry=0
  | 2021-04-08 02:06:50 INFO   Found 1 files that match "/tmp/githublog.7a1ljov7Xb.log"
```
the problem seems to be this:
```
$ retry=0
$ ((retry++))
$ echo $?
1
$ echo "${retry}"
1
```
with this fix:
```
$ retry=0
$ retry=$((retry + 1))
$ echo $?
0
$ echo "${retry}"
1
```
> Fix retry in checkout hook

- hooks/checkout
adding support for zstd on S3 checkouts. In testing zstd produced tarballs with the same or higher compression ratio while being significantly faster to extract.
> add support for zstd and aria2c

- hooks/checkout
- hooks/pre-exit
During checkout:
- read ssm parameter using ssm-cache lambda to avoid rate limit issues
- if the parameter is set, use it as proxy in git config
- also change origin to use https instead of git protocol
If the ssm parameter is not set or there is a failure calling the lambda, the proxy setting is removed
> add support for git proxy

- hooks/checkout
This fix relies on that all forms of github URLs have `<owner>/<repo>.git` in it. 
```
$ BUILDKITE_REPO=http://x-access-token:xxx@github.com/Canva/infrastructure.git bash test.sh                     
canva__infrastructure
$ BUILDKITE_REPO=https://github.com/Canva/infrastructure.git bash test.sh    
canva__infrastructure
$ BUILDKITE_REPO=org-2562356@github.com:Canva/infrastructure.git bash test.sh
canva__infrastructure
$ BUILDKITE_REPO=git@github.com:Canva/infrastructure.git bash test.sh
canva__infrastructure
$ BUILDKITE_REPO=git@github.com:Canva/infra-apps.git bash test.sh
canva__infra-apps
```
> fix print_repo_dir to parse github url in SSH or HTTP/HTTPS forms

- hooks/checkout
- hooks/pre-exit
```
GIVEN
BUILDKITE_REPO=org-2562356@github.com:Canva/infrastructure.git
proxy_url=http://git-proxy.canva-build.com:80
WILL DO
git remote set-url origin org-2562356@github.com:Canva/infrastructure.git
git config lfs.https://github.com/Canva/infrastructure.git/info/lfs.access basic
git config lfs.http://github.com/Canva/infrastructure.git/info/lfs.access basic
BUILDKITE_REPO is in git protocol and proxy do not requires authentication
Using proxy: http://git-proxy.canva-build.com:80
git config http."http://github.com/Canva/infrastructure.git".proxy http://git-proxy.canva-build.com:80
git config remote.origin.url http://github.com/Canva/infrastructure.git
git config remote.origin.pushurl org-2562356@github.com:Canva/infrastructure.git
GIVEN …
```
> [CI-769] Setting proxy based on different protocols in BUILDKITE_REPO

- hooks/checkout
Since we already have the datadog agent running in CI instances, we can send this metrics directly to datadog, this can help us keep track of checkout times for each repo.
Tested in: https://buildkite.com/canva-org/canva-check-merge/builds/378808
Metrics in datadog: https://app.datadoghq.com/metric/explorer?from_ts=1629167052704&to_ts=1629170350841&live=false&tile_size=m&exp_agg=avg&exp_row_type=metric&exp_metric=github.checkout_time&exp_scope=repo%3Acanva_canva
> report checkout duration to datadog agent

- hooks/checkout
- hooks/pre-exit
The solution is based on https://github.com/git-lfs/git-lfs/issues/2367
By adding `remote.origin.lfsurl` and `remote.origin.lfspushurl`, the git LFS will work. Without setting them, git will prompt for password or simply failed. 
Please note that regardless of using http:// or https:// for the LFS URLs, git will NOT use the proxy for LFS communications. In addition, my understand is goblet does not implement LFS cache anyway. So I just send both URLs to https://.
```
GIVEN
BUILDKITE_REPO=org-2562356@github.com:Canva/canva.git
proxy_url=https://git-proxy-2.canva-build.com
WILL DO
git remote set-url origin org-2562356@github.com:Canva/canva.git
git config lfs.https://github.com/Canva/canva.git/info/lfs.access basic
BUILDKITE_REPO is in git protocol and proxy requires authentication
Not …
```
> make git-proxy work with git LFS

- hooks/checkout
Now that we have partially rolled out Goblet to Canva/canva, it's important to know if a build failure is related to Goblet. And the reverse is true, if Goblet failed to serve a request, we want to get to the build quickly and check its logs. 
Therefore, the PR adds a `CI-Source` header to git fetch. Goblet will then log it in both Nginx and application logs. If proxy is not used, Github.com will receive this but won't do anything with it.
> Send ci source to goblet

- hooks/checkout
This is a re-implementation of the previous attempt. https://github.com/arromer/github-fetch-buildkite-plugin/pull/72
Previous attempt only worked for git fetch done by the plugin itself, but not for git commands inside the steps. As a result, majority of the Goblet logs still don't have the CI-Source header.
There are 3 options I thought about. 
1. Adding CI-Source extraHeader to existing git commands inside the steps. 
2. Changing local git config of `http.extraHeader`
3. Use `GIT_HTTP_USER_AGENT` environment variable to pass buildkite URL.
Option 1 is not easy, some of these commands are run by CI framework rather than Bash. In addition, it's not future proof. 
Option 2 is ok, but need to handle cleanup (i.e. git config --unset) upon exit.
Option 3 is the easiest. Since environment …
> send CI-Source to goblet via UserAgent instead of extraHeader

- hooks/checkout
The plugin won't checkout a repository if we're currently in an ignored
directory of another repository. For example, let assume there's a
/opt/homebrew/ repository which has a var/buildkite-agent subdirectory,
ignored by the repo. If we cd into var/buildkite-agent, and run
git rev-parse --is-inside-work-tree, it will erroneously print "true". As a
result, the checkout plugin will operate on the /opt/homebrew repo and will
fail on the git clean step. To fix this, we need to ensure that the cwd is
not ignored by the repo.
> fix: ignored directories counts as a worktree directories

- hooks/checkout
- hooks/pre-checkout
Restoring auth code previously removed in https://github.com/arromer/github-fetch-buildkite-plugin/pull/60
Needed for legacy agents still present in https://github.com/Canva/infrastructure/pull/37651
> [CI-789] Restore the legacy code for app ID and secret env vars

- hooks/checkout
This PR adds the following the the fetch plugin
1. Disable proxy after 3rd retry, regardless of rollout parameter. This is important as we are planning to increase rollout to 100% soon. 
2. Putting `github.checkout_count` metric, with tags indicating whether it's a fetch and whether it's using proxy. We can then use the data to work out the actual usage of proxy, i.e. sum(fetch=1,proxy=1) / sum(fetch=1)
Jira
https://canvadev.atlassian.net/browse/SC-30
https://canvadev.atlassian.net/browse/SC-150
> Disable proxy after 3rd retry

- hooks/checkout
fixing parsing https urls for proxy:
before:
```
$ BUILDKITE_REPO=https://github.com/Canva/canva.git
$ echo "http://github.com/${BUILDKITE_REPO#*@github.com/}"
http://github.com/https://github.com/Canva/canva.git
```
after:
```
$ BUILDKITE_REPO=https://github.com/Canva/canva.git
$ echo "http://github.com/${BUILDKITE_REPO#*github.com/}"
http://github.com/Canva/canva.git
```
and for lfs:
before
```
$ CANVA_REPO="https://github.com/Canva/canva.git"
$ echo "lfs.https://github.com/${CANVA_REPO#*@github.com/}/info/lfs.access"
lfs.https://github.com/https://github.com/Canva/canva.git/info/lfs.access
```
after
```
$ CANVA_REPO="https://github.com/Canva/canva.git"
$ echo "lfs.${CANVA_REPO}/info/lfs.access"
lfs.https://github.com/Canva/canva.git/info/lfs.access
```
> fix parsing https urls for proxy and lfs

- hooks/checkout
Goblet has supported force push since https://github.com/Canva/goblet/pull/13
So when git fetch failed, mostly likely due to timeout on Goblet or Github, the error message `"Commit SHA ${BUILDKITE_COMMIT} does not exists. The ref might have been force pushed.` is no longer relevant, and it's causing confusions.
However, it's not possible to see the real reason of failure unless we parse the log, which is not trivial since we capture the whole log of the plugin invocation. (suggestions welcome though)
Therefore, I replaced the error message with `Fail to fetch commit:${BUILDKITE_COMMIT}. Check githublog under Artifacts tab for details.`. 
Slack
https://canva.slack.com/archives/C02661K3T1D/p1651034275132599
Jira
https://canvadev.atlassian.net/browse/SC-279
> Improve error message when fetch failed

- hooks/checkout
On large repositories enumerating untracked files can take a long time. We've already done a `git reset --hard` above so there's guaranteed to be no untracked files
> Don't check untracked when running status

- hooks/checkout
Adding support to extract an archive file on macOS agents. `bsdtar` is the default `tar` on macOS and its command options differs from `gnu-tar` which is the default on ubuntu.
> Extract archive on macos

- hooks/pre-checkout
webhook objects has no reference to the actual repo checked out if MAIN_REPO is set. This PR is to set the metadata MAIN_REPO so that it will be send with the webhook object.
Note: webhook object is the json data send from buildkite upon specific events. ([link](https://buildkite.com/docs/apis/webhooks)). The one which is concerned here is `job.finished` event.
> Set build metadata if MAIN_REPO is set
